version: "3"

services:
  mlflow:
    build: .
    environment:
      - MLFLOW_TRACKING_URI=https://dagshub.com/medmabcf/N-BaIoT_mlops.mlflow 
      - MLFLOW_TRACKING_USERNAME=medmabcf 
      - MLFLOW_TRACKING_PASSWORD=25e5112253e2706993d04c88b1965215b9ed6c91 
    volumes:
      - mlflow_volume:/path/in/container
    container_name: mlflow_container

  fastapi:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    depends_on:
      - mlflow
    ports:
      - 8000:8000
    networks:
      - deploy_network
    volumes:
      - fastapi_volume:/path/in/container
    container_name: fastapi_container

networks:
  deploy_network:

volumes:
  mlflow_volume:
  fastapi_volume:
